calendarium/urls.py
"""URLs for the ``calendarium`` app."""
from django.conf.urls import patterns, url

from calendarium.views import (
    CalendariumRedirectView,
    DayView,
    EventCreateView,
    EventDeleteView,
    EventDetailView,
    EventUpdateView,
    MonthView,
    OccurrenceDeleteView,
    OccurrenceDetailView,
    OccurrenceUpdateView,
    UpcomingEventsAjaxView,
    WeekView,
)


urlpatterns = patterns(
    '',
    # event views
    url(r'^event/create/$',
        EventCreateView.as_view(),
        name='calendar_event_create'),

    url(r'^event/(?P<pk>\d+)/$',
        EventDetailView.as_view(),
        name='calendar_event_detail'),

    url(r'^event/(?P<pk>\d+)/update/$',
        EventUpdateView.as_view(),
        name='calendar_event_update'),

    url(r'^event/(?P<pk>\d+)/delete/$',
        EventDeleteView.as_view(),
        name='calendar_event_delete'),

    # occurrence views
    url(r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        OccurrenceDetailView.as_view(),
        name='calendar_occurrence_detail'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/update/$',  # NOPEP8
        OccurrenceUpdateView.as_view(),
        name='calendar_occurrence_update'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/delete/$',  # NOPEP8
        OccurrenceDeleteView.as_view(),
        name='calendar_occurrence_delete'),

    # calendar views
    url(r'^(?P<year>\d+)/(?P<month>\d+)/$',
        MonthView.as_view(),
        name='calendar_month'),

    url(r'^(?P<year>\d+)/week/(?P<week>\d+)/$',
        WeekView.as_view(),
        name='calendar_week'),

    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        DayView.as_view(),
        name='calendar_day'),

    url(r'^get-events/$',
        UpcomingEventsAjaxView.as_view(),
        name='calendar_upcoming_events'),

    url(r'^$',
        CalendariumRedirectView.as_view(),
        name='calendar_current_month'),

)

mailsend/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('mailsend',
	url(r'^$', 'views.feedback', name='feedback'),
)

mailsender/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^calendar/', include('calendarium.urls')),
    url(r'^mailsend/', include('mailsend.urls')),
    url(r'^', include('app_mailsender.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

calendarium/forms.py
"""Forms for the ``calendarium`` app."""
from django import forms
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.utils.timezone import datetime, timedelta

from calendarium.constants import (
    OCCURRENCE_DECISION_CHOICESS,
    OCCURRENCE_DECISIONS,
)
from calendarium.models import Event, Occurrence


class OccurrenceForm(forms.ModelForm):
    """A form for the ``Occurrence`` model."""
    decision = forms.CharField(
        widget=forms.Select(choices=OCCURRENCE_DECISION_CHOICESS),
    )

    cancelled = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    original_start = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    original_end = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    event = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Event.objects.all(),
    )

    class Meta:
        model = Occurrence
        exclude = []

    def save(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['decision'] == OCCURRENCE_DECISIONS['all']:
            changes = dict(
                (key, value) for key, value in cleaned_data.iteritems()
                if value != self.initial.get(key) and self.initial.get(key))
            event = self.instance.event
            # for each field on the event, check for new data in cleaned_data
            for field_name in [field.name for field in event._meta.fields]:
                value = changes.get(field_name)
                if value:
                    setattr(event, field_name, value)
            event.save()

            # repeat for persistent occurrences
            for occ in event.occurrences.all():
                for field_name in [field.name for field in occ._meta.fields]:
                    value = changes.get(field_name)
                    if value:
                        # since we can't just set a new datetime, we have to
                        # adjust the datetime fields according to the changes
                        # on the occurrence form instance
                        if type(value) != datetime:
                            setattr(occ, field_name, value)
                        else:
                            initial_time = self.initial.get(field_name)
                            occ_time = getattr(occ, field_name)
                            delta = value - initial_time
                            new_time = occ_time + delta
                            setattr(occ, field_name, new_time)
                occ.save()

            # get everything from initial and compare to cleaned_data to
            # retrieve what has been changed
            # apply those changes to the persistent occurrences (and the main
            # event)
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['this one']:
            self.instance.save()
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['following']:
            # get the changes
            changes = dict(
                (key, value) for key, value in cleaned_data.iteritems()
                if value != self.initial.get(key) and self.initial.get(key))

            # change the old event
            old_event = self.instance.event
            end_recurring_period = self.instance.event.end_recurring_period
            old_event.end_recurring_period = self.instance.start - timedelta(
                days=1)
            old_event.save()

            # the instance occurrence holds the info for the new event, that we
            # use to update the old event's fields
            new_event = old_event
            new_event.end_recurring_period = end_recurring_period
            new_event.id = None
            event_kwargs = model_to_dict(self.instance)
            for field_name in [field.name for field in new_event._meta.fields]:
                if (field_name == 'created_by'
                        and event_kwargs.get('created_by')):
                    value = User.objects.get(pk=event_kwargs.get(field_name))
                elif field_name in ['rule', 'category']:
                    continue
                else:
                    value = event_kwargs.get(field_name)
                if value:
                    setattr(new_event, field_name, value)
            new_event.save()

calendarium/views.py
"""Views for the ``calendarium`` app."""
import calendar
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from django.http import Http404, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.utils.timezone import datetime, now, timedelta, utc
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView,
    TemplateView,
    UpdateView,
)

from .constants import OCCURRENCE_DECISIONS
from .forms import OccurrenceForm
from .models import EventCategory, Event, Occurrence
from .settings import SHIFT_WEEKSTART
from .utils import monday_of_week


class CategoryMixin(object):
    """Mixin to handle category filtering by category id."""
    def dispatch(self, request, *args, **kwargs):
        if hasattr(self, 'category'):
            # If we already have a category on the class, then we probably
            # already went through the CategorySlugMixin
            return super(CategoryMixin, self).dispatch(
                request, *args, **kwargs)

        if request.GET.get('category'):
            try:
                category_id = int(request.GET.get('category'))
            except ValueError:
                pass
            else:
                try:
                    self.category = EventCategory.objects.get(pk=category_id)
                except EventCategory.DoesNotExist:
                    pass
        return super(CategoryMixin, self).dispatch(request, *args, **kwargs)

    def get_category_context(self, **kwargs):
        context = {'categories': EventCategory.objects.all()}
        if hasattr(self, 'category'):
            context.update({'current_category': self.category})
        return context


class CategorySlugMixin(CategoryMixin):
    """Mixin to handle category filtering by category slug."""
    def dispatch(self, request, *args, **kwargs):
        if request.GET.get('category'):
            try:
                self.category = EventCategory.objects.get(
                    slug=request.GET.get('category'))
            except EventCategory.DoesNotExist:
                pass
        return super(CategorySlugMixin, self).dispatch(
            request, *args, **kwargs)


class CalendariumRedirectView(RedirectView):
    """View to redirect to the current month view."""
    def get_redirect_url(self, **kwargs):
        return reverse('calendar_month', kwargs={'year': now().year,
                                                 'month': now().month})


class MonthView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for a whole month."""
    template_name = 'calendarium/calendar_month.html'

    def dispatch(self, request, *args, **kwargs):
        self.month = int(kwargs.get('month'))
        self.year = int(kwargs.get('year'))
        if self.month not in range(1, 13):
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                new_date = datetime(self.year, self.month, 1) + timedelta(
                    days=31)
                return HttpResponseRedirect(reverse('calendar_month', kwargs={
                    'year': new_date.year, 'month': new_date.month}))
            elif request.POST.get('previous'):
                new_date = datetime(self.year, self.month, 1) - timedelta(
                    days=1)
                return HttpResponseRedirect(reverse('calendar_month', kwargs={
                    'year': new_date.year, 'month': new_date.month}))
            elif request.POST.get('today'):
                return HttpResponseRedirect(reverse('calendar_month', kwargs={
                    'year': now().year, 'month': now().month}))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_month.html'
        return super(MonthView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        firstweekday = 0 + SHIFT_WEEKSTART
        while firstweekday < 0:
            firstweekday += 7
        while firstweekday > 6:
            firstweekday -= 7

        ctx = self.get_category_context()
        month = [[]]
        week = 0
        start = datetime(year=self.year, month=self.month, day=1, tzinfo=utc)
        end = datetime(
            year=self.year, month=self.month, day=1, tzinfo=utc
        ) + relativedelta(months=1)

        all_occurrences = Event.objects.get_occurrences(
            start, end, ctx.get('current_category'))
        cal = calendar.Calendar()
        cal.setfirstweekday(firstweekday)
        for day in cal.itermonthdays(self.year, self.month):
            current = False
            if day:
                date = datetime(year=self.year, month=self.month, day=day,
                                tzinfo=utc)
                occurrences = filter(
                    lambda occ, date=date: occ.start.replace(
                        hour=0, minute=0, second=0, microsecond=0) == date,
                    all_occurrences)
                if date.date() == now().date():
                    current = True
            else:
                occurrences = []
            month[week].append((day, occurrences, current))
            if len(month[week]) == 7:
                month.append([])
                week += 1
        calendar.setfirstweekday(firstweekday)
        weekdays = [_(header) for header in calendar.weekheader(10).split()]
        ctx.update({'month': month, 'date': date, 'weekdays': weekdays})
        return ctx


class WeekView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for one week."""
    template_name = 'calendarium/calendar_week.html'

    def dispatch(self, request, *args, **kwargs):
        self.week = int(kwargs.get('week'))
        self.year = int(kwargs.get('year'))
        if self.week not in range(1, 53):
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                date = monday_of_week(self.year, self.week) + timedelta(days=7)
                return HttpResponseRedirect(reverse('calendar_week', kwargs={
                    'year': date.year, 'week': date.date().isocalendar()[1]}))
            elif request.POST.get('previous'):
                date = monday_of_week(self.year, self.week) - timedelta(days=7)
                return HttpResponseRedirect(reverse('calendar_week', kwargs={
                    'year': date.year, 'week': date.date().isocalendar()[1]}))
            elif request.POST.get('today'):
                return HttpResponseRedirect(reverse('calendar_week', kwargs={
                    'year': now().year,
                    'week': now().date().isocalendar()[1]}))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_week.html'
        return super(WeekView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = self.get_category_context()
        date = monday_of_week(self.year, self.week) + relativedelta(
            days=SHIFT_WEEKSTART)
        week = []
        day = SHIFT_WEEKSTART
        start = date
        end = date + relativedelta(days=7 + SHIFT_WEEKSTART)
        all_occurrences = Event.objects.get_occurrences(
            start, end, ctx.get('current_category'))
        while day < 7 + SHIFT_WEEKSTART:
            current = False
            occurrences = filter(
                lambda occ, date=date: occ.start.replace(
                    hour=0, minute=0, second=0, microsecond=0) == date,
                all_occurrences)
            if date.date() == now().date():
                current = True
            week.append((date, occurrences, current))
            day += 1
            date = date + timedelta(days=1)
        ctx.update({'week': week, 'date': date, 'week_nr': self.week})
        return ctx


class DayView(CategoryMixin, TemplateView):
    """View to return all occurrences of an event for one day."""
    template_name = 'calendarium/calendar_day.html'

    def dispatch(self, request, *args, **kwargs):
        self.day = int(kwargs.get('day'))
        self.month = int(kwargs.get('month'))
        self.year = int(kwargs.get('year'))
        try:
            self.date = datetime(year=self.year, month=self.month,
                                 day=self.day, tzinfo=utc)
        except ValueError:
            raise Http404
        if request.method == 'POST':
            if request.POST.get('next'):
                date = self.date + timedelta(days=1)
                return HttpResponseRedirect(reverse('calendar_day', kwargs={
                    'year': date.year, 'month': date.month, 'day': date.day}))
            elif request.POST.get('previous'):
                date = self.date - timedelta(days=1)
                return HttpResponseRedirect(reverse('calendar_day', kwargs={
                    'year': date.year, 'month': date.month, 'day': date.day}))
            elif request.POST.get('today'):
                return HttpResponseRedirect(reverse('calendar_day', kwargs={
                    'year': now().year, 'month': now().month,
                    'day': now().day}))
        if request.is_ajax():
            self.template_name = 'calendarium/partials/calendar_day.html'
        return super(DayView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = self.get_category_context()
        occurrences = Event.objects.get_occurrences(
            self.date, self.date, ctx.get('current_category'))
        ctx.update({'date': self.date, 'occurrences': occurrences})
        return ctx


class EventDetailView(DetailView):
    """View to return information of an event."""
    model = Event


class EventMixin(object):

calendarium/templates/calendarium/calendar_day.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Occurrences" %}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" name="previous" value="{% trans "Previous" %}" />
    <input type="submit" name="next" value="{% trans "Next" %}" />
    <input type="submit" name="today" value="{% trans "Today" %}" />
</form>
<table class="table">
    <tr>
        <th>{{ date|date:'D m/d' }}</th>
    </tr>
    <tr>
        {% for occurrence in occurrences %}
            <td><p>{{ occurrence }}</p></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

calendarium/templates/calendarium/calendar_month.html
{% extends "base.html" %}
{% load i18n calendarium_tags %}

{% block main %}
<h1>{{ date|date:"F Y" }}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input class="btn btn-default" type="submit" name="previous" value="{% trans "Previous" %}" />
    <input class="btn btn-default" type="submit" name="next" value="{% trans "Next" %}" />
    <input class="btn btn-default" type="submit" name="today" value="{% trans "Today" %}" />
    {% if request.user.is_staff %}
        <a href="{% url "calendar_event_create" %}">{% trans "Create new event" %}</a>
    {% endif %}
</form>
<table class="table" id="calendar-month">
    <tr>
        <th></th>
        {% for weekday in weekdays %}
            <th>{{ weekday }}</th>
        {% endfor %}
    </tr>
    {% for week in month %}
        {% if week %}
            <tr>
                <td class="calendarium-week-link"><a href="{{ date|get_week_URL:week.0.0 }}">{% trans "View" %}</a></td>
                {% for day, occurrences, current in week %}
                    <td class="{% if day == 0 %}calendarium-empty{% elif current %}calendarium-current{% else %}calendarium-day{% endif %}">
                        <div class="calendarium-relative">
                            {% if day != 0 %}
                                <span class="calendarium-date">{{ day }}</span>
                                {% for occurrence in occurrences %}
                                    <p class="alert" style="background-color: #{{ occurrence.event.category.color }}">
                                        <a title="{{ occurrence }}" href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">{{ occurrence|truncatechars:22 }}</a>
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                {% endfor %}
            </tr>
        {% endif %}
    {% endfor %}
</table>
{% render_upcoming_events 5 current_category %}
{% endblock %}

calendarium/templates/calendarium/calendar_week.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Occurrences" %}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" name="previous" value="{% trans "Previous" %}" />
    <input type="submit" name="next" value="{% trans "Next" %}" />
    <input type="submit" name="today" value="{% trans "Today" %}" />
</form>
<table class="table" id="calendar-week">
    <tr>
        {% for date, occurrences, current in week %}
            <th><a href="{% url "calendar_day" year=date|date:'Y' month=date|date:'m' day=date|date:'d' %}">{{ date|date:'D m/d' }}</a></th>
        {% endfor %}
    </tr>
    <tr>
        {% for date, occurrences, current in week %}
            <td class="{% if current %}calendarium-current{% endif %}">
                <div class="calendarium-relative">
                    <span class="calendarium-day-dame">{{ date|date:'D m/d' }}</span>
                    {% for occurrence in occurrences %}
                        <p class="alert">
                            <a href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">{{ occurrence|truncatechars:22 }}</a>
                        </p>
                    {% endfor %}
                    <a class="calendarium-day-link" href="{% url "calendar_day" year=date|date:'Y' month=date|date:'m' day=date|date:'d' %}">{% trans "View calendar day" %}</a>
                </div>
            </td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

calendarium/templates/calendarium/event_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action=".">
    {% csrf_token %}
    {% trans "Do you really want to delete this event?" %}
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

calendarium/templates/calendarium/event_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{{ object }}</h1>
<table>
    <tr>
        <th>{% trans "Start" %}</th>
        <td>{{ object.start }}</td>
    </tr>
    <tr>
        <th>{% trans "End" %}</th>
        <td>{{ object.end }}</td>
    </tr>
    <tr>
        <th>{% trans "Category" %}</th>
        <td>{{ object.category }}</td>
    </tr>
    <tr>
        <th>{% trans "Description" %}</th>
        <td>{{ object.description }}</td>
    </tr>
</table>
<a href="javascript:history.back();">{% trans "back" %}</a>
{% if request.user.is_staff %}
    <a href="{% url "calendar_event_update" pk=object.pk %}">{% trans "Edit" %}</a>
    <a href="{% url "calendar_event_delete" pk=object.pk %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

calendarium/templates/calendarium/event_form.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>
    {% if form.instance.id %}
        {% trans "Update" %} {{ form.instance }}
    {% else %}
        {% trans "Create event" %}
    {% endif %}
</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}" />
</form>
{% if form.instance.id %}
    <a href="{% url "calendar_event_delete" pk=form.instance.pk %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

calendarium/templates/calendarium/occurrence_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action="{% url "calendar_occurrence_delete" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">
    {% csrf_token %}
    <p>
        <label for="id_event">{% trans "Decision" %}:</label>
        <select name="decision">
            {% for decision in decisions %}
                <option value="{{ decision }}">{{ decision }}</option>
            {% endfor %}
        </select>
    </p>
    <a href="{% url "calendar_occurrence_update" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">{% trans "Back" %}</a>
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

calendarium/templates/calendarium/occurrence_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{{ object }}</h1>
<table>
    <tr>
        <th>{% trans "Start" %}</th>
        <td>{{ object.start }}</td>
    </tr>
    <tr>
        <th>{% trans "End" %}</th>
        <td>{{ object.end }}</td>
    </tr>
    <tr>
        <th>{% trans "Category" %}</th>
        <td>{{ object.category }}</td>
    </tr>
    <tr>
        <th>{% trans "Description" %}</th>
        <td>{{ object.description }}</td>
    </tr>
</table>
<a href="javascript:history.back();">{% trans "back" %}</a>
{% if request.user.is_staff %}
    <a href="{% url "calendar_occurrence_update" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">{% trans "Edit" %}</a>
    <a href="{% url "calendar_occurrence_delete" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

calendarium/templates/calendarium/occurrence_form.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>
    {% if form.instance.id %}
        {% trans "Update" %} {{ form.instance }}
    {% else %}
        {% trans "Create event" %}
    {% endif %}
</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}" />
</form>
<a href="{% url "calendar_occurrence_delete" pk=form.instance.event.pk year=form.instance.start.year month=form.instance.start.month day=form.instance.start.day %}">{% trans "Delete" %}</a>
{% endblock %}

calendarium/templates/calendarium/upcoming_events.html
<ul>
    {% for occurrence in occurrences %}
        <li>{{ occurrence.title }}</li>
    {% endfor %}
</ul>